### ISSUE TITLE
Log shows incorrect number of files that will be deleted

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#115]
**Describe the bug**
When installing an application for the first time and trivrost downloading the bundle for the first time, it also logs how many local files it will delete.

It shows 
I 0.316 Deleting 100 files, 100 of which will be updated in "/home/x/.local/share/y/z/bundles/zz". [launcher/bundle/update_bundle.go:deleteChangedFiles():144]
eventho no files are locally deleted.

**To Reproduce**
Install a new bundle and check the log.

**Comment by MMulthaupt** [comment]
This _might_ be just a wording issue, as in trivrost will really try to delete those 100 files before writing the new ones, but simply ignore if they did not previously exist. Will take a look at this when appropriate.

**Comment by dragetd** [comment]
It might be just a case of wording it differently.

But do we have the info of how many local files will be actually deleted? Because this might be actually useful. :D
