### ISSUE TITLE
Windows runner fails if there are tests in the gui package

### ISSUE THREAD

**Issue by MMulthaupt** [setlog/trivrost#188]
If the package `cmd/launcher/gui` contains tests, Windows runner will fail. See https://github.com/setlog/trivrost/runs/1165922354?check_suite_focus=true#step:6:123

This is likely related to the use of CGO within the package. The closest similar issue I could find online is https://travis-ci.community/t/cgo-and-exit-status-3221225781/2015 where the cause were missing DLLs. It would be good to understand why this is happening.

Alternatively, we could get rid of CGO by using `syscall`. We could also try to push for the addition of more functions in https://godoc.org/golang.org/x/sys/windows (which supercedes `syscall` as per [the syscall package's documentation](https://golang.org/pkg/syscall/?GOOS=windows)).

The WINAPI functions we would need are:
- `MonitorFromWindow()`
- `GetMonitorInfo()`
- `GetWindowRect()`
- `SetWindowPos()`
- `FlashWindowEx()`
- `ExtractIconExW()`
- `SendMessage()`
- `SetWindowLong()`

**Comment by dragetd** [comment]
We have fixed this.
