### ISSUE TITLE
Include certificate information in logfiles

### ISSUE THREAD

**Issue by ma-assbrock** [setlog/trivrost#205]
Some companies do a man-in-the-middle attack on every TLS connection, so they can scan every connection for security stuff. They do so by terminating the TLS connection, scanning it for malicious content and re-encrypting it via TLS with a certificate that is not globally trusted.

If the root CA for the man-in-the-middle attack is added to the trusted root CAs of the operating system of our end-user, this works mostly fine. However, the security solution doing the man-in-the-middle might change the content. (We saw one case in which an html-document with an error message was passed instead of the original file, as the original file was falsely detected as malware.) In this case trivrost detects that the file was changed, because the checksum does not match. (trivrost is designed in such a way that it should be secure, even if TLS is broken.)

The only problem is that the log file does not explicitly show that a man-in-the-middle-attack took place.

We should print the certificate—or at least its fingerprints—in the logs.

Printing it for every connection would spam the log files a lot. So we should print every fingerprint exactly once in a log file.

**Comment by dragetd** [comment]
Fixed #242
