### ISSUE TITLE
Allow signing under Linux

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#241]
Allow signing under Linux

**Comment by ma-assbrock** [comment]
https://stackoverflow.com/questions/18287960/signing-windows-application-on-linux-based-distros

**Comment by dragetd** [comment]
Once #12 is fixed (maybe by #162), we will no longer have signing as a fixed part of trivrost. We can document how to do it, but I would not keep it in the makefile to be honest.

This is more of an internal CI issue. Can I close this issue?

**Comment by ma-assbrock** [comment]
I close the issue.
