### ISSUE TITLE
Relicense to MIT

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#46]
We have discussed internally a lot under which license we want to go OpenSource with.

GPLv3 forces people to return fixes back to us. But on the other hand, they would have to deliver a link to the sources - which is a PITA.

My suggestion is: MIT. It is copyleft and allows almost anything. The copyright notes have to stay with the source files if they are distributed… so we might thing about adding these to all of the source files.

We should decide this before our first v1.3.0 release!

**Comment by dragetd** [comment]
Needs feedback (an OK) from current contributers @MMulthaupt @dchaykin @ma-assbrock

**Comment by MMulthaupt** [comment]
OK

**Comment by ma-assbrock** [comment]
OK
