### ISSUE TITLE
Use Pull-Requests for releases through master

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#54]
Thinking about our releasing process, as soon as we have a pipeline anymore (#47), a release on master must always run successfully through the pipeline.

Since this should be the case on develop, it should always be the case on master when doing a release. Unless we mess up and accidentally merge the wrong commits, which can happen in the CLI. So my idea I got from another team: We could use PRs also to merge into master. This would allow even others to comment and check the pipeline via GitHub and make the release more straight-forward.

Of course, when using development as the branch to base the PR on, an 'accidental' commit on develop could end up in the release during the PR is open. The chance of this happening with our workflow or even if, then causing a problem, is extremely minimal.

What are you thoughts?

**Comment by MMulthaupt** [comment]
Isn't [this change](https://github.com/setlog/trivrost/pull/53/files#diff-6a3371457528722a734f3c51d9238c13R46) good enough?

**Comment by MMulthaupt** [comment]
I guess we can just try it.

**Comment by dragetd** [comment]
Next time we will try! :)
