### ISSUE TITLE
Current timestamp security mechanism is broken

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#57]
Currently, we implemented the timestamp mechanism to prevent downgrade-attacks on bundles. The timestamp is unique per bundle-name tho. Nothing prevents an attack from downgrading a client to another signed but older (and vulnerable) bundle (e.g. for jre versions: downgrade from amazon-corretto-8u222 to adopenopenjdk-8u202).

This scenario is only relevant if the attacker is already able to MITM the connection. In a second step the attack would need a local attack vector against the application, since this is the only thing depending on the downgraded bundle.
This is a pretty low-risk scenario.

And we have decided to never change bundles anyways. A new version of a bundle is a new bundlename. In that case, we do not even need this functionality at all.

I suggest removing it.

**Comment by ma-assbrock** [comment]
> Nothing prevents an attack from downgrading a client to another signed but older (and vulnerable) bundle (e.g. for jre versions: downgrade from amazon-corretto-8u222 to adopenopenjdk-8u202).

The deployment config itself is signed and has a timestamp. This should prevent such an attack.

But, the attacker could deliver a vulnerable bundle under the URL of the correct bundle (in a MITM scenario). We would have to add the bundle name in the deployment config to prevent this attack.

As a workarround you could sign every bundle with a different private key and only include those public keys in trivrost, that are relevant for your application.

**Comment by dragetd** [comment]
After a voip discussion we agreed, that the mechanism is still valid as Marc described. But this issue will stay open to document the advantages and problems of unique bundles which are mutable or immutable.
