### ISSUE TITLE
EvalSymlink crashes trivrost on mounted disks

### ISSUE THREAD

**Issue by dragetd** [setlog/trivrost#86]
We internally discovered a bug that causes trivrost to crash within the EvalSymlink function if the user-profile is a driveletter-less NTFS mount.

We suspect a golang bug, further investigation will be reported here.

**Comment by dragetd** [comment]
Testing v1.2.1 in Windows 10.

golang v1.12.1:
works

golang v1.12.12:
works

golang v1.13
fails

golang v1.13.3
fails

regression confirmed!

I'll update the documentation.

**Comment by MMulthaupt** [comment]
Are there plans to write a report for this [in the Golang Github project](https://github.com/golang/go/issues)?

**Comment by dragetd** [comment]
We have added a workaround. The issue where this had been discussed was https://github.com/golang/go/issues/20506 which is closed. I vaguely remember that there was another issue about this on the golang project, but I personally do not have the time to follow up on this.

Feel free, but we close this bug!
